### PR TITLE
Closes #16 - Update home page documentation to improve clarity

### LINKED ISSUE #16: Update home page documentation to improve clarity
## Problem/Motivation

The home page currently displays: 

- "Arizona Bootstrap", and links to AZ Bootstrap (BS4)
- "Arizona Quickstart", and links to UA Quickstart (D7)

This can be confusing since UA Quickstart (D7) uses UA Bootstrap (BS3). And AZ Quickstart (D9) uses AZ Bootstrap (BS4).

## Recommended Change

Update the documentation so it's more clear how the 4 projects are different from one another (since the change from UA to AZ doesn't make it obvious for anyone outside of Friday meetings group).

1.) Update the home page so that it's linking to and describing UA Bootstrap (BS3)

2.) Improve the descriptions so that it's more clear which projects correspond to which versions of Quickstart & Bootstrap

2.) Add in a placeholder for Quickstart 2.0 (no link/coming soon) since it's currently in development

### PR DESCRIPTION
**Pull request by akslay**
Closes #16 by updating the verbiage/documentation on the digital.arizona.edu home page. The current home page is a little confusing and has some mismatched links. This update attempts to clarify the differences between our 2 versions of Bootstrap and 2 versions of Quickstart. Also cleaned up the HTML and appearance while I was in there.

Would appreciate feedback on the wording I used for each project--just went with what I thought made the most sense with the content we already have on that page.

I used "Pre-release coming winter 2020" on the Quickstart 2.0 card, since we discussed that date during our last workshop. But "Pre-release coming soon" might be better?

### CODE REVIEW

**Comment by akslay** [comment]
**Before update:**
digital_before


**After update:**
digital_after

**Review by camikazegreen — APPROVED** [review]

**Comment by joeparsons** [comment]
This looks great, overall! 😍 

The only feedback I have is that I think it'd be good to replace the word "view" with something else on the `View UA Bootstrap`, `View Arizona Bootstrap`, and `View UA Quickstart` link buttons.  Maybe `Explore UA Bootstrap`, etc?

**Comment by joeparsons** [comment]
One other thing:  Should we add a Red Bar to this page?

**Comment by akslay** [comment]
> This looks great, overall! 😍
> 
> The only feedback I have is that I think it'd be good to replace the word "view" with something else on the `View UA Bootstrap`, `View Arizona Bootstrap`, and `View UA Quickstart` link buttons. Maybe `Explore UA Bootstrap`, etc?

Sold!

**Comment by akslay** [comment]
> One other thing: Should we add a Red Bar to this page?

I was thinking about doing that as well, but I wasn't sure if I should or not since it's not technically part of Bootstrap as a component. But this site also isn't Bootstrap docs, so it might be fine?

**Comment by joeparsons** [comment]
> I was thinking about doing that as well, but I wasn't sure if I should or not since it's not technically part of Bootstrap as a component. But this site also isn't Bootstrap docs, so it might be fine?

I think it's high time we add a Red Bar component to Arizona Bootstrap, too.

**Comment by akslay** [comment]
> > I was thinking about doing that as well, but I wasn't sure if I should or not since it's not technically part of Bootstrap as a component. But this site also isn't Bootstrap docs, so it might be fine?
> 
> I think it's high time we add a Red Bar component to Arizona Bootstrap, too.

For the purpose of this PR, should I just point to the same img that we use on our Quickstart sites? (https://brand.arizona.edu/sites/default/files/digital-resources/ua_wordmark_line_logo_white_rgb.svg)

**Comment by joeparsons** [comment]
> For the purpose of this PR, should I just point to the same img that we use on our Quickstart sites? (https://brand.arizona.edu/sites/default/files/digital-resources/ua_wordmark_line_logo_white_rgb.svg)

That makes sense to me although @trackleft is probably the best person to answer that.

**Comment by akslay** [comment]
> > For the purpose of this PR, should I just point to the same img that we use on our Quickstart sites? (https://brand.arizona.edu/sites/default/files/digital-resources/ua_wordmark_line_logo_white_rgb.svg)
> 
> That makes sense to me although @trackleft or @barrettbaffert are probably the best people to answer that.

Sounds good--I'll add it in for now and then we can change it if needed.

**Review by joeparsons — DISMISSED** [review]

**Review by camikazegreen — DISMISSED** [review]

**Review by trackleft — DISMISSED** [review]
Nice, thanks.

**Review by mmunro-ltrr — DISMISSED** [review]

**Review by kevcooper — APPROVED** [review]

**Review by trackleft — APPROVED** [review]

**Pull request merged**
